name: learn-github-actions
on: 
  workflow_dispatch:
    inputs:
        server_test_url:
          description: 'Enter server test url'
          required: true
          type: string
        user_phone_number:
          description: 'Enter phone number of user for test'
          required: true
          type: string
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v